### ISSUE TITLE
Afazeres de um pet

### ISSUE THREAD

**Issue by LSinzker** [EngSwCIC/CICBook#24]
Eu como usuário quero adicionar afazeres relacionados a cada pet.

**Comment by jhosoume** [comment]
História de usuário relacionada a editar, criar e deletar um afazer.
* Adicionar tabela no banco de dados 

Afazeres != necessidades?
A princípio, pensei em necessidades como relacionadas a espécie, seriam recorrentes. Afazeres seriam separados da espécie e esporádicas.

**Comment by jhosoume** [comment]
Ahh, inclusive talvez esteja relacionada com https://github.com/EngSwCIC/PleaseDontDie/issues/6
